### ISSUE TITLE
Error on startup "There was an error registering application commands"

### ISSUE THREAD

**Issue by TacoV** [dandln/TheEpicAudioStreamer#12]
Directly following startup info, I get an error

``` CMD
[14:18:32 INF] Welcome to TEASConsole, version 0.6.2
[14:18:33 INF] The device "VB-Audio Virtual Cable" will be used in this session
[14:18:33 INF] Chosen audio device is VB-Audio Virtual Cable
[14:18:33 INF] The bot will accept commands from users [snip]
[14:18:33 INF] DSharpPlus, version 4.4.0-nightly-01376
[14:18:34 FTL] There was an error registering application commands
DSharpPlus.Exceptions.UnauthorizedException: Unauthorized: 403
   at DSharpPlus.Net.DiscordApiClient.BulkOverwriteGuildApplicationCommandsAsync(UInt64 application_id, UInt64 guild_id, IEnumerable`1 commands)
   at DSharpPlus.SlashCommands.SlashCommandsExtension.<>c__DisplayClass39_0.<<RegisterCommands>b__0>d.MoveNext()
```

**Comment by TacoV** [comment]
I re-ran the authorization steps in https://github.com/dandln/TheEpicAudioStreamer#preparing-the-bot and now everything works again!

**Comment by dandln** [comment]
Yup, this will happen when the bot either isn't in the server that is passed to the bot through the Guild ID, or if it doesn't have the right permissions to run slash commands. Glad it was an easy fix! :)
